myblog_django/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import blog
import users.views
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", blog.views.MainView.as_view(), name='index'),
    path("login/", users.views.login, name='login'),
    path("logout/", users.views.logout, name='logout'),
    path("registration/", users.views.registration, name='registration'),
    path("profile/", users.views.profile, name='profile'),
    path("post/", views.PostDetail.as_view(), name='post'),
    path("contact/", views.ContactForm.as_view(), name='contact'),
    path('user/', include('users.urls', namespace='user')),
    #path("", blog.views.index),
]

#if settings.DEBUG:
#    urlpatterns += [
#        path("__debug__/", include("debug_toolbar.urls")),
#    ]

# Для возможности закачки файлов

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]

blog/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')
    phone_number = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

    username = forms.CharField()
    password = forms.CharField()



class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )
    
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()



class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",)

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

blog/views.py
from django.shortcuts import render
from django.views import View


class MainView(View):
    def get(self, request, *args, **kwargs):
        title = 'My Blog - Главная'
        message = ''
        context = {
            'title': title,
            "message": message
        }
        return render(request,'blog/index.html', context=context)



class PostDetail(View):
    def get(self, request, *args, **kwargs):
        title = 'My Blog - Пост'
        message = ''
        context = {
            'title': title,
            "message": message
        }
        return render(request, 'blog/post.html', context=context)


class ContactForm(View):
    def get(self, request, *args, **kwargs):
        title = 'My Blog - Сообщение'
        message = ''
        context = {
            'title': title,
            "message": message
        }
        return render(request, 'blog/contact.html', context=context)



def index(request):
    title = 'Главная'
    message = ''
    context = {
        'title': title,
        "message": message
        }
    return render(request, 'blog/index.html', context=context)

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse


from users.forms import ProfileForm, UserLoginForm, UserRegistrationForm



def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            session_key = request.session.session_key

            if user:
                auth.login(request, user)
                messages.success(request, f"{username}, Вы вошли в аккаунт")

                redirect_page = request.POST.get('next', None)
                if redirect_page and redirect_page != reverse('logout'):
                    return HttpResponseRedirect(request.POST.get('next'))
                    
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()

    context = {
        'title': 'Home - Авторизация',
        'form': form
    }
    return render(request, 'users/login.html', context)



def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()

            session_key = request.session.session_key

            user = form.instance
            auth.login(request, user)

            messages.success(request, f"{user.username}, Вы успешно зарегистрированы и вошли в аккаунт")
            return HttpResponseRedirect(reverse('index'))
    else:
        form = UserRegistrationForm()
    
    context = {
        'title': 'Home - Регистрация',
        'form': form
    }
    return render(request, 'users/registration.html', context)

@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Профайл успешно обновлен")
            return HttpResponseRedirect(reverse('profile'))
    else:
        form = ProfileForm(instance=request.user)

    context = {
        'title': 'Home - Кабинет',
        'form': form,
    }
    return render(request, 'users/profile.html', context)



@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, Вы вышли из аккаунта")
    auth.logout(request)
    return redirect(reverse('index'))

blog/templates/blog/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block header %}
    {% include 'includes/slider.html' %}
{% endblock %}

{% block content %}
                    <div class="row justify-content-center">
                        <div class="col-6">
                            <p class="lead">Чтобы связаться со мной заполните форму обратной связи</p>
                            <form name="contact-form" action="">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="md-form mb-0">
                                            <label for="name" class="visually-hidden">Ваше имя</label>
                                            <input type="text" id="name" class="form-control" placeholder="Ваше имя">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="md-form mb-0">
                                            <label for="email" class="visually-hidden">Ваша почта</label>
                                            <input type="text" id="email" class="form-control" placeholder="Ваша почта">
                                        </div>
                                    </div>
                                </div>

                                <div class="row mt-3">
                                    <div class="col-md-12">
                                        <div class="md-form mb-0">
                                            <label for="subject" class="visually-hidden">Тема</label>
                                            <input type="text" id="subject" class="form-control" placeholder="Тема">
                                        </div>
                                    </div>
                                </div>

                                <div class="row mt-3">
                                    <div class="col-md-12">
                                        <div class="md-form">
                                            <label for="message" class="visually-hidden">Ваше сообщение</label>
                                            <textarea type="text" id="message" rows="2" class="form-control md-textarea" placeholder="Ваше сообщение"></textarea>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <div class="text-center text-md-start my-3">
                                <button class="btn btn-primary" type="submit">Отправить</button>
                            </div>
                        </div>
                    </div>

{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block header %}
    {% include 'includes/slider.html' %}
{% endblock %}

{% block content %}
    <div class="container">
      <h1 class="my-3">Последние записи блога</h1>
      <div class="row">
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img src="{% static "img/img1.jpg" %}" alt="" class="card-img-top">
            <div class="card-body">
              <h4 class="card-title">Заголовок</h4>
              <p class="card-text">Это красткое описание поста. Это красткое описание поста. Это красткое описание поста. </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="#" class="btn btn-sm btn-outline-secondary">Подробнее</a>
                </div>
                <small class="text-muted">22.10.2020</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img src="{% static "img/img2.jpg" %}" alt="" class="card-img-top">
            <div class="card-body">
              <h4 class="card-title">Заголовок</h4>
              <p class="card-text">Это красткое описание поста. Это красткое описание поста. Это красткое описание поста. </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="#" class="btn btn-sm btn-outline-secondary">Подробнее</a>
                </div>
                <small class="text-muted">21.10.2020</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img src="{% static "img/img3.jpg" %}" alt="" class="card-img-top">
            <div class="card-body">
            <h4 class="card-title">Заголовок</h4>
            <p class="card-text">Это красткое описание поста. Это красткое описание поста. Это красткое описание поста. </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="#" class="btn btn-sm btn-outline-secondary">Подробнее</a>
                </div>
                <small class="text-muted">20.10.2020</small>
              </div>
            </div>
          </div>
        </div>

{% endblock %}

{% block pagination %}
    <nav aria-label="Paginate me">
      <ul class="pagination justify-content-center">
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1">Предыдущая</a>
        </li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item">
          <a class="page-link" href="#">Следующая</a>
        </li>
      </ul>
    </nav>
    <br>
{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--    TITLE УНИКАЛЬНЫЙ -->
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
  </head>
  <body>

    <!--    НАВИГАЦИЯ ВЕЗДЕ ОДИНАКОВАЯ -->
    {% include './includes/navbar.html' %}

    <!--    СЛАЙДЕР ТОЛЬКО НА ГЛАВНОЙ, ГДЕ-ТО ВМЕСТО НЕГО ПРОСТО ХЭДЭР, А ГДЕ-ТО ЕГО НЕТ -->
    {% block header %}{% endblock %}

    <!--    ОСНОВНОЙ БЛОК КОНТЕНТА. ВЕЗДЕ РАЗНОЕ КОЛ-ВО КОЛОНОК -->
    {% block content %}{% endblock %}

    <!--    ПАГИНАЦИЯ ГДЕ-ТО ЕСТЬ А ГДЕ-ТО НЕТУ -->
    {% block pagination %}{% endblock %}

<!--    ФУТЕР ВЕЗДЕ ОДИНАКОВЫЙ -->
{% include './includes/footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="js/script.js"></script>
  </body>
</html>

templates/includes/footer.html
<section class="my-footer mt-3">
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
  <symbol id="python" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M14 4.5V14a2 2 0 0 1-2 2H7v-1h5a1 1 0 0 0 1-1V4.5h-2A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v9H2V2a2 2 0 0 1 2-2h5.5L14 4.5ZM0 11.85h1.6c.289 0 .533.06.732.179.201.117.355.276.46.477.105.201.158.427.158.677 0 .25-.054.476-.16.677-.106.199-.26.357-.464.474a1.452 1.452 0 0 1-.732.173H.79v1.342H0V11.85Zm2.06 1.714a.795.795 0 0 0 .085-.381c0-.227-.062-.4-.185-.521-.123-.122-.294-.182-.513-.182H.788v1.406h.66a.794.794 0 0 0 .374-.082.574.574 0 0 0 .238-.24Zm2.963.75v1.535H4.23v-1.52L2.89 11.85h.876l.853 1.696h.032l.856-1.696h.855l-1.339 2.464Z"/>
  </symbol>
  <symbol id="telegram" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.287 5.906c-.778.324-2.334.994-4.666 2.01-.378.15-.577.298-.595.442-.03.243.275.339.69.47l.175.055c.408.133.958.288 1.243.294.26.006.549-.1.868-.32 2.179-1.471 3.304-2.214 3.374-2.23.05-.012.12-.026.166.016.047.041.042.12.037.141-.03.129-1.227 1.241-1.846 1.817-.193.18-.33.307-.358.336a8.154 8.154 0 0 1-.188.186c-.38.366-.664.64.015 1.088.327.216.589.393.85.571.284.194.568.387.936.629.093.06.183.125.27.187.331.236.63.448.997.414.214-.02.435-.22.547-.82.265-1.417.786-4.486.906-5.751a1.426 1.426 0 0 0-.013-.315.337.337 0 0 0-.114-.217.526.526 0 0 0-.31-.093c-.3.005-.763.166-2.984 1.09z"/>
  </symbol>
</svg>
  <div class="container">
    <div class="row">
      <div class="col-lg-9 col-sm-12 my-3">
        <a href="/" class="text-body-secondary text-decoration-none lh-1">
          <svg class="bi" width="30" height="24"><use xlink:href="#python"/></svg>
        </a>
        <span class="text-body-secondary">&copy; 2024 Агентство по разработке потрясных сайтов на bootstrap, django, drf, fastapi, vue3.js и nuxtJS. А это просто наш блог.</span>
      </div>
      <div class="col-lg-3 col-sm-12 my-3 d-flex justify-content-end">
        <ul class="nav list-unstyled">
          <li class=""><a class="text-body-secondary" href="https://t.me/nord_dron_spb"><svg class="bi" width="24" height="24"><use xlink:href="#telegram"/></svg></a></li>
          <li class="ms-2"><a class="text-end" href="#">Наверх</a></li>
        </ul>
      </div>
    </div>
  </div>
</section>

templates/includes/navbar.html
<section class="my-navigation">
      <nav class="navbar navbar-expand-lg bg-body-tertiary"  data-bs-theme="dark">
          <div class="container-fluid">
              <a href="#" class="navbar-brand">
                  <img src="https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg" width="30" height="30" alt="Python">
              </a>
              <a href="#" class="navbar-brand">
                  <img src="https://upload.wikimedia.org/wikipedia/commons/a/ae/Nuxt_logo.svg" width="30" height="30" alt="NuxtJS">
              </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <div class="navbar-nav me-auto mb-2 mb-lg-0">
                      <a class="nav-link active" aria-current="page" href="{% url "index" %}">Главная</a>
                      <a class="nav-link" href="{% url "contact" %}">Контакты</a>
                  </div>
                  <form class="d-flex" role="search">
                      <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Поиск">
                      <button class="btn btn-outline-success me-2" type="submit">Найти</button>
                  </form>
                      {% if not user.is_authenticated %}
                          <a type="button" class="btn btn-outline-light me-2" href="{% url "login" %}">Вход</a>
                          <a type="button" class="btn btn-outline-light me-2" href="{% url "registration" %}">Регистрация</a>
                      {% endif %}
                      {% if user.is_admin %}
                          <a type="button" class="btn btn-outline-light me-2" href="{% url "admin:index" %}">Админ панель</a>
                      {% endif %}
                      {% if user.is_authenticated %}
                          <a type="button" class="btn btn-outline-light me-2" href="{% url "profile" %}">Профайл</a>
                          <a type="button" class="btn btn-outline-light" href="{% url "logout" %}">Выход</a>
                      {% endif %}


            </div>
          </div>
      </nav>
</section>

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="row">
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                <h2 class="text-center mb-4">Авторизация</h2>
                <form  action="{% url "user:login" %}" method="post">
                    {% csrf_token %}
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value={{request.GET.next}}>
                    {% endif %}
                    <div class="mb-3">
                        <label for="id_username" class="form-label">Имя пользователя</label>
                        <input type="text" class="form-control"
                        value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                        name="username" id="id_username"
                        placeholder="Введите ваше имя пользователя"
                        required>
                    </div>
                    <div class="mb-3">
                        <label for="id_password" class="form-label">Пароль</label>
                        <input type="password" class="form-control" name="password" id="id_password"
                        placeholder="Введите ваш пароль" required>
                    </div>


                    <button type="submit" class="btn btn-dark btn-block">Войти</button>
                </form>
                <div class="mt-3">
                    <a href="#">Забыли пароль?</a> | <a href="{% url "user:registration" %}">Создать аккаунт</a>
                </div>
                <hr>
                <div class="text-center">
                    <p>Или авторизуйтесь через:</p>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/google.svg" %}" alt="Catalog Icon" width="16" height="16">
                        Google
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/facebook.svg" %}" alt="Catalog Icon" width="16" height="16">
                        Facebook
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/facebook.svg" %}" alt="Catalog Icon" width="16" height="16">
                        GitHub
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

users/templates/users/logout.html
{% extends "base.html" %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row">
            <!-- Профиль с данными пользователя -->
            <div class="col-md-5">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Профиль пользователя</h3>
                    <form action="{% url "users:profile" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12 mb-3 text-center">
                                {% if user.image %}
                                    <img src="{{ user.image.url }}"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                {% else %}
                                    <img src="{% static "img/baseavatar.jpg" %}"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                {% endif %}
                                <input type="file" class="form-control mt-3" id="id_image"
                                    name='image'
                                    accept="image/*">
                                    {% if form.image.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_first_name" class="form-label">Имя*</label>
                                <input type="text" class="form-control" id="id_first_name"
                                    name="first_name"
                                    placeholder="Введите ваше имя"
                                    value="{{ form.first_name.value }}"
                                    required>
                                    {% if form.first_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_last_name" class="form-label">Фамилия*</label>
                                <input type="text" class="form-control" id="id_last_name"
                                    name="last_name"
                                    placeholder="Введите вашу фамилию"
                                    value="{{ form.last_name.value }}"
                                    required>
                                    {% if form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_username" class="form-label">Имя пользователя*</label>
                                <input type="text" class="form-control" id="id_username"
                                    name="username"
                                    placeholder="Введите ваше имя пользователя"
                                    value="{{ form.username.value }}"
                                    required>
                                    {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                    name="email"
                                    placeholder="Введите ваш email *youremail@example.com"
                                    value="{{ form.email.value }}"
                                    required>
                                    {% if form.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                    {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Сохранить</button>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock  %}

users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Регистрация</h2>
                <form action="{% url "user:registration" %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Имя*</label>
                            <input type="text" class="form-control" id="id_first_name"
                                value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                name="first_name"
                                placeholder="Введите ваше имя" required>
                                {% if form.first_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Фамилия*</label>
                            <input type="text" class="form-control" id="id_last_name"
                                value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                name="last_name"
                                placeholder="Введите вашу фамилию" required>
                                {% if form.last_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_username" class="form-label">Имя пользователя*</label>
                            <input type="text" class="form-control" id="id_username"
                                value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                name="username"
                                placeholder="Введите ваше имя пользователя" required>
                                {% if form.username.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Email*</label>
                            <input type="email" class="form-control" id="id_email"
                                value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                name="email"
                                placeholder="Введите ваш email" required>
                                {% if form.email.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password1" class="form-label">Пароль*</label>
                            <input type="password" class="form-control" id="id_password1"
                                value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                                name="password1"
                                placeholder="Введите пароль" required>
                                {% if form.password1.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                            <input type="password" class="form-control" id="id_password2"
                                value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                                name="password2"
                                placeholder="Подтвердите пароль" required>
                                {% if form.password2.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
                                {% endif %}
                        </div>
                    </div>
                    <button type="submit"
                        class="btn btn-dark btn-block">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock  %}